[CmdletBinding()]
param([string]$SourceRoot='C:\ai-lab-core-recovery',[string]$InstallRoot='C:\ai-lab-core',[string]$OutputRoot='C:\Users\domai\AppData\Local\Temp\NEXT-STABIL-R04-VERSION-20260927')
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$compose=Join-Path $InstallRoot 'compose.yaml';$core=Join-Path $InstallRoot 'operations\runtime\approved-compose\R04-D21-P3-core.override.yml';$envFile=Join-Path $InstallRoot '.env';$relative='operations\runtime\approved-compose\R04-FINAL-VERSION.override.yml';$target=Join-Path $InstallRoot $relative;$source=Join-Path $SourceRoot $relative;$manifest=Join-Path $InstallRoot 'operations\runtime\startup-set.json';$pre=Join-Path $OutputRoot 'preimages';New-Item -ItemType Directory -Path $pre -Force|Out-Null
if(-not(Test-Path -LiteralPath $envFile -PathType Leaf)){throw 'COMPOSE_ENV_FILE_MISSING'}
if(Test-Path $target){throw 'VERSION_OVERRIDE_PREIMAGE_EXPECTED_ABSENT'};$manifestHash=(Get-FileHash $manifest -Algorithm SHA256).Hash;if($manifestHash-ne'53CA6E98F81915D62C7695D8F077FACC95E394D897BD2E9D12000143B6972EC9'){throw 'MANIFEST_PREIMAGE_MISMATCH'};Copy-Item $manifest (Join-Path $pre 'startup-set.json')
$names=@('ai-lab-backend','postgres','qdrant','n8n','open-webui','ollama');$before=@{};foreach($n in $names){$before[$n]=(& docker.exe inspect -f '{{.Id}}' $n).Trim();if($LASTEXITCODE-ne0){throw "CONTAINER_PREIMAGE_FAILED:$n"}}
$journal=[ordered]@{operation_id='R04-FINAL-VERSION-POLICY-20260927';status='PREIMAGES_CAPTURED';manifest_sha256=$manifestHash;override='ABSENT_PREIMAGE';containers=$before};$journal|ConvertTo-Json -Depth 5|Set-Content (Join-Path $OutputRoot 'journal.json') -Encoding UTF8
try{
 Copy-Item $source $target;if((Get-FileHash $source -Algorithm SHA256).Hash-ne(Get-FileHash $target -Algorithm SHA256).Hash){throw 'VERSION_OVERRIDE_POSTIMAGE_MISMATCH'}
 & docker.exe compose --env-file $envFile -p ai-lab-core -f $compose -f $core -f $target up -d --no-deps --force-recreate backend;if($LASTEXITCODE-ne0){throw 'BACKEND_REPLACEMENT_FAILED'}
 $deadline=(Get-Date).AddMinutes(3);do{Start-Sleep 2;try{$health=Invoke-RestMethod http://127.0.0.1:8000/health -TimeoutSec 3}catch{$health=$null}}while($null-eq$health-and(Get-Date)-lt$deadline);if($null-eq$health){throw 'BACKEND_READINESS_FAILED'}
 foreach($n in $names|Where-Object{$_-ne'ai-lab-backend'}){$id=(& docker.exe inspect -f '{{.Id}}' $n).Trim();if($id-ne$before[$n]){throw "NON_BACKEND_ID_CHANGED:$n"}}
 $newId=(& docker.exe inspect -f '{{.Id}}' ai-lab-backend).Trim();$image=(& docker.exe inspect -f '{{.Image}}' ai-lab-backend).Trim();if($image-ne'sha256:6342b36fa2cdd2501ea4e0e9fada9a9ffaa4894f0c512f19f822f009e8d63702'){throw 'BACKEND_IMAGE_CHANGED'}
 $version=Invoke-RestMethod http://127.0.0.1:8000/version -TimeoutSec 10;if($version.version-ne'1.0.2'-or$version.latest_app_version-ne'1.0.2'-or$version.minimum_app_version-ne'1.0.0'-or$version.environment-ne'production'-or$version.debug-ne$false-or$version.component_identity.runtime_configuration-ne'SAFE'){throw 'VERSION_READBACK_MISMATCH'}
 $m=Get-Content $manifest -Raw|ConvertFrom-Json;$m.set_id='R04-FINAL-EXECUTION-20260927';$m.approval.set_id=$m.set_id;$m.approval.decision_id='R04-FINAL-EXECUTION';($m.containers|Where-Object{$_.service-eq'backend'}).container_id=$newId;$hash=(Get-FileHash $target -Algorithm SHA256).Hash;$entry=[pscustomobject]@{role='backend_version_override';path=$relative.Replace('\','/');sha256=$hash;evidence='R04_FINAL_VERSION_POLICY_INSTALLED_20260927'};$m.files=@($m.files|Where-Object{$_.role-ne'backend_version_override'})+$entry;$tmp="$manifest.tmp-$PID";$m|ConvertTo-Json -Depth 100|Set-Content $tmp -Encoding UTF8;Move-Item $tmp $manifest -Force
 $journal.status='COMPLETE';$journal.backend_before=$before['ai-lab-backend'];$journal.backend_after=$newId;$journal.version=$version;$journal.manifest_sha256=(Get-FileHash $manifest -Algorithm SHA256).Hash;$journal|ConvertTo-Json -Depth 8|Set-Content (Join-Path $OutputRoot 'journal.json') -Encoding UTF8;$journal|ConvertTo-Json -Depth 8|Set-Content (Join-Path $OutputRoot 'result.json') -Encoding UTF8
}catch{
 $failure=$_;if(Test-Path $target){Remove-Item $target -Force};& docker.exe compose --env-file $envFile -p ai-lab-core -f $compose -f $core up -d --no-deps --force-recreate backend|Out-Null;Copy-Item (Join-Path $pre 'startup-set.json') $manifest -Force;$journal.status='ROLLED_BACK';$journal.failure=[string]$failure;$journal|ConvertTo-Json -Depth 8|Set-Content (Join-Path $OutputRoot 'journal.json') -Encoding UTF8;throw
}
