[CmdletBinding()]
param([string]$SourceRoot='C:\ai-lab-core-recovery',[string]$InstallRoot='C:\ai-lab-core',[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{40}$')][string]$SourceRevision,[string]$OutputRoot='C:\Users\domai\AppData\Local\Temp\NEXT-STABIL-R04-FINAL-CLOSURE-20260927')
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$operationId='R04-FINAL-CLOSURE-WORKER-BACKUP-20260927';$expectedManifest='51EC9B4D58F32CD8D72A21A24F3AAEEA14994EEF92E943933788209C2128EAB9';$expectedVersionOverride='4F55994D8258090BC92120A46C48E053877971307297C5CF06F4EF4FC29F0D82';$backendImage='sha256:6342b36fa2cdd2501ea4e0e9fada9a9ffaa4894f0c512f19f822f009e8d63702'
$manifest=Join-Path $InstallRoot 'operations\runtime\startup-set.json';$versionRelative='operations\runtime\approved-compose\R04-FINAL-VERSION.override.yml';$versionTarget=Join-Path $InstallRoot $versionRelative;$compose=Join-Path $InstallRoot 'compose.yaml';$core=Join-Path $InstallRoot 'operations\runtime\approved-compose\R04-D21-P3-core.override.yml';$envFile=Join-Path $InstallRoot '.env';$pre=Join-Path $OutputRoot 'preimages';New-Item -ItemType Directory -Path $pre -Force|Out-Null
function Get-TreeInventory([string]$Path){$root=(Resolve-Path -LiteralPath $Path).Path.TrimEnd('\');$items=@(Get-ChildItem -LiteralPath $root -Recurse -Force -File|Sort-Object FullName);$lines=@($items|ForEach-Object{"$($_.FullName.Substring($root.Length).Replace('\','/').ToLowerInvariant())|$($_.Length)|$((Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant())"});$bytes=[Text.Encoding]::UTF8.GetBytes(($lines-join"`n"));$sha=[Security.Cryptography.SHA256]::Create();[pscustomobject]@{files=$items.Count;bytes=[int64](($items|Measure-Object Length -Sum).Sum);aggregate_sha256=([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','');acl=(Get-Acl -LiteralPath $root).Sddl;reparse=[bool]((Get-Item -LiteralPath $root -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)}}
function Copy-Tree([string]$From,[string]$To){New-Item -ItemType Directory -Path $To -Force|Out-Null;& robocopy.exe $From $To /E /COPY:DATS /DCOPY:DAT /R:1 /W:1 /NFL /NDL /NJH /NJS /NP|Out-Null;if($LASTEXITCODE-ge8){throw "TREE_COPY_FAILED:$From"}}
function Assert-Tree([string]$A,[string]$B,[string]$Role){$x=Get-TreeInventory $A;$y=Get-TreeInventory $B;if($x.files-ne$y.files-or$x.bytes-ne$y.bytes-or$x.aggregate_sha256-ne$y.aggregate_sha256-or$x.acl-ne$y.acl-or$y.reparse){throw "TREE_VERIFY_FAILED:$Role"};$x}
function Write-Utf8NoBom([string]$Path,[string]$Text){[IO.File]::WriteAllText($Path,$Text,(New-Object Text.UTF8Encoding($false)))}
if((Get-FileHash $manifest -Algorithm SHA256).Hash-ne$expectedManifest){throw 'MANIFEST_PREIMAGE_MISMATCH'};if((Get-FileHash $versionTarget -Algorithm SHA256).Hash-ne$expectedVersionOverride){throw 'VERSION_OVERRIDE_PREIMAGE_MISMATCH'};if(-not(Test-Path $envFile -PathType Leaf)){throw 'COMPOSE_ENV_FILE_MISSING'}
$installed=Get-Content $manifest -Raw|ConvertFrom-Json;if($installed.approval.status-ne'APPROVED_FOR_START'-or$installed.approval.set_id-ne$installed.set_id){throw 'MANIFEST_NOT_APPROVED'};$versionBinding=$installed.files|Where-Object{$_.role-eq'backend_version_override'};if($null-eq$versionBinding-or$versionBinding.sha256-ne$expectedVersionOverride){throw 'VERSION_BINDING_MISMATCH'}
$liveVersion=Invoke-RestMethod 'http://127.0.0.1:8000/version' -TimeoutSec 10;if($liveVersion.version-ne'1.0.2'-or$liveVersion.latest_app_version-ne'1.0.2'-or$liveVersion.minimum_app_version-ne'1.0.0'-or$liveVersion.environment-ne'production'-or$liveVersion.debug-ne$false-or$liveVersion.component_identity.runtime_configuration-ne'SAFE'){throw 'VERSION_POLICY_PREIMAGE_MISMATCH'}
$filePreimages=[ordered]@{'operations\supervisor\server.js'='4CFB7F9E3D97521D8D0F6D588BB119AB34C9D52FAD498AA520368CD13B170701';'operations\supervisor\analysis_queue.js'='F26E521CB50B76FB35BB28A09C0919167164F1E11131FD7E7CE39FBA4EF05CAA';'operations\supervisor\vision_queue.js'='37B0AFFDB2D3C355E4377BE4EF905CC1A8EFCCE635089B8E002D5445C8505F33';'operations\vision-worker\vision-job.js'='A059A64B1BD7658990A8A14ACD03D433697792FBCC6C231D18319AB48EFCFB9A';'operations\vision-worker\analysis-job.js'='2D9E4B0B639D052611F57C5A17AF7DAD415E5D7BAA78349C420BF3E13B2C971C';'operations\vision-worker\package.json'='ABSENT_PREIMAGE';'operations\vision-worker\package-lock.json'='ABSENT_PREIMAGE';'backend\app\scripts\run_backup_schedule.py'='975207C0F319A728A587F4823CAA77CA6FBFD01C96B8F1880C300FF782718108';'operations\hardening\run-backup-schedule.ps1'='33A5CABC5726FAEEE44BB708CC93ACC7817A65CEB7FC436D23FBE6CE8437441A';'operations\hardening\backup-production.ps1'='25BD1F12B237A603D2C19323C175E3220ECFA2E8B97FAB48B05D3DE3CCEB4DDE';'operations\hardening\invoke-qdrant-backup-helper.ps1'='ABSENT_PREIMAGE'}
$fileRecords=@();foreach($rel in $filePreimages.Keys){$target=Join-Path $InstallRoot $rel;$want=$filePreimages[$rel];$exists=Test-Path $target -PathType Leaf;if($want-eq'ABSENT_PREIMAGE'){if($exists){throw "PREIMAGE_EXPECTED_ABSENT:$rel"};$fileRecords+=[pscustomobject]@{relative=$rel;state='ABSENT_PREIMAGE';backup=$null}}else{if(-not$exists-or(Get-FileHash $target -Algorithm SHA256).Hash-ne$want){throw "PREIMAGE_MISMATCH:$rel"};$backup=Join-Path $pre $rel;New-Item -ItemType Directory -Path (Split-Path $backup -Parent)-Force|Out-Null;Copy-Item $target $backup;$fileRecords+=[pscustomobject]@{relative=$rel;state='EXACT_BYTES';backup=$backup}}};Copy-Item $manifest (Join-Path $pre 'startup-set.json');Copy-Item $versionTarget (Join-Path $pre 'version.override.yml')
$dataLink=Get-Item (Join-Path $InstallRoot 'data') -Force;if(-not($dataLink.Attributes-band[IO.FileAttributes]::ReparsePoint)-or@($dataLink.Target)-notcontains'D:\ai-lab-data'){throw 'ACTIVE_DATA_JUNCTION_MISMATCH'}
$directorySpecs=@([pscustomobject]@{role='worker_modules';source='C:\ChatGPT-Vision-Worker\worker\node_modules';target=(Join-Path $InstallRoot 'operations\vision-worker\node_modules')},[pscustomobject]@{role='worker_state';source='C:\ChatGPT-Vision-Worker';target=(Join-Path $InstallRoot 'data\workers\chatgpt-vision')});$directoryRecords=@();foreach($spec in $directorySpecs){if(Test-Path $spec.target -PathType Container){$backup=Join-Path $pre $spec.role;Copy-Tree $spec.target $backup;$directoryRecords+=[pscustomobject]@{role=$spec.role;target=$spec.target;state='EXACT_DIRECTORY';backup=$backup;inventory=(Get-TreeInventory $spec.target)}}else{$directoryRecords+=[pscustomobject]@{role=$spec.role;target=$spec.target;state='ABSENT_DIRECTORY_PREIMAGE';backup=$null;inventory=$null}}}
$active=Get-CimInstance Win32_Process|Where-Object{$_.Name-match'(?i)^node(\.exe)?$'-and$_.CommandLine-match'(?i)(vision-job|analysis-job|ChatGPT-Vision-Worker)'};if($active){throw 'WORKER_PROCESS_ACTIVE'};$sourceReparse=Get-ChildItem -LiteralPath 'C:\ChatGPT-Vision-Worker' -Recurse -Force|Where-Object{$_.Attributes-band[IO.FileAttributes]::ReparsePoint};if($sourceReparse){throw 'WORKER_SOURCE_REPARSE_POINT'}
$names=@('ai-lab-backend','postgres','qdrant','n8n','open-webui','ollama');$containerBefore=@{};foreach($n in $names){$containerBefore[$n]=(& docker.exe inspect -f '{{.Id}}' $n).Trim();if($LASTEXITCODE-ne0){throw "CONTAINER_PREIMAGE_FAILED:$n"}};$backendShapeBefore=(& docker.exe inspect -f '{{json .HostConfig.Binds}}|{{json .HostConfig.PortBindings}}|{{.HostConfig.NetworkMode}}|{{.HostConfig.RestartPolicy.Name}}' ai-lab-backend).Trim()
$journal=[ordered]@{schema='NEXT_STABIL_R04_MUTATION_JOURNAL_V1';operation_id=$operationId;source_revision=$SourceRevision;started_utc=[DateTime]::UtcNow.ToString('o');status='PREIMAGES_CAPTURED_NO_MUTATION';pending_mutation=$false;files=$fileRecords;directories=$directoryRecords;containers=$containerBefore;rollback='NOT_NEEDED'};$journalPath=Join-Path $OutputRoot 'mutation-journal.json';$journal|ConvertTo-Json -Depth 8|Set-Content $journalPath -Encoding UTF8
$moduleStage=$null;$stateStage=$null
try{
 $moduleStage=Join-Path (Split-Path $directorySpecs[0].target -Parent) ('.r04-stage-node_modules-'+$PID);$stateStage=Join-Path (Split-Path $directorySpecs[1].target -Parent) ('.r04-stage-chatgpt-vision-'+$PID);Copy-Tree $directorySpecs[0].source $moduleStage;$moduleInventory=Assert-Tree $directorySpecs[0].source $moduleStage 'worker_modules';New-Item -ItemType Directory -Path $stateStage -Force|Out-Null;foreach($name in @('edge-profile','input','logs','output','rollback')){$src=Join-Path $directorySpecs[1].source $name;if(Test-Path $src -PathType Container){Copy-Tree $src (Join-Path $stateStage $name)}};if((Get-Item $stateStage).Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'STATE_STAGE_REPARSE_POINT'}
 $journal.status='MUTATION_STARTED';$journal.pending_mutation=$true;$journal|ConvertTo-Json -Depth 8|Set-Content $journalPath -Encoding UTF8;foreach($record in $directoryRecords){if(Test-Path $record.target){Remove-Item $record.target -Recurse -Force}};Move-Item $moduleStage $directorySpecs[0].target;Move-Item $stateStage $directorySpecs[1].target;foreach($record in $directoryRecords){if((Get-Item $record.target).Attributes-band[IO.FileAttributes]::ReparsePoint){throw "TARGET_REPARSE_POINT:$($record.role)"}}
 $files=@($filePreimages.Keys);foreach($rel in $files){$src=Join-Path $SourceRoot $rel;$dst=Join-Path $InstallRoot $rel;Copy-Item $src $dst -Force;if((Get-FileHash $src -Algorithm SHA256).Hash-ne(Get-FileHash $dst -Algorithm SHA256).Hash){throw "POSTIMAGE_MISMATCH:$rel"}}
 $releaseId='NEXT-STABIL-R04-'+$SourceRevision.Substring(0,16);$override="services:`n  backend:`n    image: $backendImage`n    pull_policy: never`n    environment:`n      APP_VERSION: `"1.0.2`"`n      MINIMUM_APP_VERSION: `"1.0.0`"`n      LATEST_APP_VERSION: `"1.0.2`"`n      RELEASE_ID: `"$releaseId`"`n      SOURCE_REVISION: `"$SourceRevision`"`n      BACKEND_IMAGE_DIGEST: `"$backendImage`"`n      ENVIRONMENT: `"production`"`n      DEBUG: `"false`"`n";$overrideTmp="$versionTarget.tmp-$PID";Write-Utf8NoBom $overrideTmp $override;Move-Item $overrideTmp $versionTarget -Force;$overrideHash=(Get-FileHash $versionTarget -Algorithm SHA256).Hash
 & docker.exe compose --env-file $envFile -p ai-lab-core -f $compose -f $core -f $versionTarget up -d --no-deps --force-recreate backend;if($LASTEXITCODE-ne0){throw 'BACKEND_REPLACEMENT_FAILED'};$deadline=(Get-Date).AddMinutes(3);do{Start-Sleep 2;try{$health=Invoke-RestMethod 'http://127.0.0.1:8000/health' -TimeoutSec 3}catch{$health=$null}}while($null-eq$health-and(Get-Date)-lt$deadline);if($null-eq$health){throw 'BACKEND_READINESS_FAILED'};foreach($n in $names|Where-Object{$_-ne'ai-lab-backend'}){if((& docker.exe inspect -f '{{.Id}}' $n).Trim()-ne$containerBefore[$n]){throw "NON_BACKEND_ID_CHANGED:$n"}};$backendAfter=(& docker.exe inspect -f '{{.Id}}' ai-lab-backend).Trim();if((& docker.exe inspect -f '{{.Image}}' ai-lab-backend).Trim()-ne$backendImage){throw 'BACKEND_IMAGE_CHANGED'};if((& docker.exe inspect -f '{{json .HostConfig.Binds}}|{{json .HostConfig.PortBindings}}|{{.HostConfig.NetworkMode}}|{{.HostConfig.RestartPolicy.Name}}' ai-lab-backend).Trim()-ne$backendShapeBefore){throw 'BACKEND_RUNTIME_SHAPE_CHANGED'};$envLines=& docker.exe inspect -f '{{range .Config.Env}}{{println .}}{{end}}' ai-lab-backend;foreach($flag in @('DATABASE_STARTUP_SEED_ENABLED','BACKUP_PLAN_RECONCILER_ENABLED','VISION_AUTOMATION_ENABLED','VISUAL_V2_ENABLED','ADVANCED_ANALYSIS_ENABLED','KNOWLEDGE_BASE_PROCESSING_ENABLED','KNOWLEDGE_BASE_VECTOR_WRITES_ENABLED','DOCUMENT_PREPARATION_ENABLED','ASSISTANT_PIPELINE_V2_ENABLED')){if(@($envLines|Where-Object{$_-eq"$flag=false"}).Count-ne1){throw "BACKEND_FLAG_NOT_FALSE:$flag"}}
 $final=Get-Content $manifest -Raw|ConvertFrom-Json;$final.set_id='R04-FINAL-CLOSURE-'+$SourceRevision.Substring(0,12);$final.approval.set_id=$final.set_id;$final.approval.decision_id='R04-FINAL-CLOSURE-20260927';($final.containers|Where-Object{$_.service-eq'backend'}).container_id=$backendAfter;$roles=[ordered]@{'operations\supervisor\server.js'='supervisor_script';'operations\supervisor\analysis_queue.js'='analysis_queue';'operations\supervisor\vision_queue.js'='vision_queue';'operations\vision-worker\vision-job.js'='vision_worker';'operations\vision-worker\analysis-job.js'='analysis_worker';'operations\vision-worker\package.json'='worker_package';'operations\vision-worker\package-lock.json'='worker_package_lock';'backend\app\scripts\run_backup_schedule.py'='backup_schedule_backend';'operations\hardening\run-backup-schedule.ps1'='backup_schedule_runner';'operations\hardening\backup-production.ps1'='backup_production';'operations\hardening\invoke-qdrant-backup-helper.ps1'='qdrant_backup_helper'};foreach($rel in $roles.Keys){$role=$roles[$rel];$final.files=@($final.files|Where-Object{$_.role-ne$role})+[pscustomobject]@{role=$role;path=$rel.Replace('\','/');sha256=(Get-FileHash (Join-Path $InstallRoot $rel)-Algorithm SHA256).Hash;evidence='R04_FINAL_CLOSURE_INSTALLED_20260927'}};$final.files=@($final.files|Where-Object{$_.role-ne'backend_version_override'})+[pscustomobject]@{role='backend_version_override';path=$versionRelative.Replace('\','/');sha256=$overrideHash;evidence='R04_FINAL_CLOSURE_INSTALLED_20260927'}
 $stateChecks=@();foreach($name in @('edge-profile','input','logs','output','rollback')){$src=Join-Path $directorySpecs[1].source $name;if(Test-Path $src -PathType Container){$stateChecks+=Assert-Tree $src (Join-Path $directorySpecs[1].target $name) "worker_state_$name"}};$null=Assert-Tree $directorySpecs[0].source $directorySpecs[0].target 'worker_modules'
 $manifestTmp="$manifest.tmp-$PID";Write-Utf8NoBom $manifestTmp (($final|ConvertTo-Json -Depth 100)+"`n");Move-Item $manifestTmp $manifest -Force;. (Join-Path $InstallRoot 'operations\runtime\startup-runtime.ps1');$read=Read-StartupSetManifest -ManifestPath $manifest;$validation=Test-StartupSetManifest -Manifest $read.manifest -ManifestPath $manifest -ExpectedRoot $InstallRoot;if(-not$validation.valid){throw "MANIFEST_VALIDATION_FAILED:$($validation.errors-join',')"};$postVersion=Invoke-RestMethod 'http://127.0.0.1:8000/version' -TimeoutSec 10;if($postVersion.component_identity.backend.source_revision-ne$SourceRevision-or$postVersion.component_identity.release_id-ne$releaseId-or$postVersion.component_identity.runtime_configuration-ne'SAFE'){throw 'FINAL_VERSION_READBACK_MISMATCH'}
 $journal.status='COMPLETE';$journal.pending_mutation=$false;$journal.rollback='NOT_NEEDED';$journal.finished_utc=[DateTime]::UtcNow.ToString('o');$journal.backend_after=$backendAfter;$journal.manifest_sha256=(Get-FileHash $manifest -Algorithm SHA256).Hash;$journal.version_override_sha256=$overrideHash;$journal|ConvertTo-Json -Depth 10|Set-Content $journalPath -Encoding UTF8;$result=[ordered]@{status='INSTALLED';operation_id=$operationId;source_revision=$SourceRevision;release_id=$releaseId;pending_mutation=$false;manifest_sha256=$journal.manifest_sha256;version_override_sha256=$overrideHash;backend_id=$backendAfter;modules=(Get-TreeInventory $directorySpecs[0].target);state=(Get-TreeInventory $directorySpecs[1].target);old_source_preserved=(Test-Path 'C:\ChatGPT-Vision-Worker');journal=$journalPath};$result|ConvertTo-Json -Depth 8|Set-Content (Join-Path $OutputRoot 'install-result.json') -Encoding UTF8
}catch{
 $failure=$_;$journal.status='ROLLBACK_STARTED';$journal.pending_mutation=$true;$journal.failure=[string]$failure;$journal|ConvertTo-Json -Depth 10|Set-Content $journalPath -Encoding UTF8;foreach($record in $fileRecords){$target=Join-Path $InstallRoot $record.relative;if($record.state-eq'EXACT_BYTES'){Copy-Item $record.backup $target -Force}elseif(Test-Path $target){Remove-Item $target -Force}};foreach($record in $directoryRecords){if(Test-Path $record.target){Remove-Item $record.target -Recurse -Force};if($record.state-eq'EXACT_DIRECTORY'){Copy-Tree $record.backup $record.target}};Copy-Item (Join-Path $pre 'version.override.yml') $versionTarget -Force;& docker.exe compose --env-file $envFile -p ai-lab-core -f $compose -f $core -f $versionTarget up -d --no-deps --force-recreate backend|Out-Null;Copy-Item (Join-Path $pre 'startup-set.json') $manifest -Force;foreach($p in @($moduleStage,$stateStage)){if($p-and(Test-Path $p)){Remove-Item $p -Recurse -Force}};$journal.status='FAILED_ROLLED_BACK';$journal.pending_mutation=$false;$journal.rollback='COMPLETE';$journal.finished_utc=[DateTime]::UtcNow.ToString('o');$journal|ConvertTo-Json -Depth 10|Set-Content $journalPath -Encoding UTF8;$journal|ConvertTo-Json -Depth 10|Set-Content (Join-Path $OutputRoot 'install-result.json') -Encoding UTF8;throw
}
