'use strict';
const crypto=require('crypto');const fs=require('fs');const path=require('path');const {spawn}=require('child_process');
const {TemporaryChatArbiter}=require('./temporary_chat_arbiter');const {validatePackage}=require('../vision-worker/analysis_contract');
function write(file,v){const temp=`${file}.${process.pid}.tmp`;fs.writeFileSync(temp,`${JSON.stringify(v,null,2)}\n`);fs.renameSync(temp,file);}function read(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function inside(root,candidate){const base=`${fs.realpathSync(root)}${path.sep}`.toLowerCase();return fs.realpathSync(candidate).toLowerCase().startsWith(base);}
class AnalysisQueue{
 constructor({spoolRoot,workerScript,workerRoot,spawnWorker,arbiter}={}){this.root=path.resolve(spoolRoot);this.jobs=path.join(this.root,'jobs');this.incoming=path.join(this.root,'incoming');this.workerScript=workerScript;this.workerRoot=workerRoot;this.spawnWorker=spawnWorker||this._spawn.bind(this);this.arbiter=arbiter||new TemporaryChatArbiter();this.queue=[];this.active=null;this.pausedState=null;fs.mkdirSync(this.jobs,{recursive:true});fs.mkdirSync(this.incoming,{recursive:true});this.recover();}
 recover(){for(const e of fs.readdirSync(this.jobs,{withFileTypes:true})){if(!e.isDirectory())continue;const s=this.get(e.name);if(s&&['QUEUED','RUNNING'].includes(s.state)){s.state='QUEUED';write(path.join(this.jobs,e.name,'status.json'),s);this.queue.push(e.name);}else if(s&&['AUTH_REQUIRED','UI_CHANGED'].includes(s.state)&&s.attempt_count<2)this.pausedState=s.state;}if(this.pausedState)this.arbiter.pause(this.pausedState);setImmediate(()=>this.pump());}
 health(){return{status:this.pausedState||(this.active?'BUSY':'READY'),active_job_id:this.active?.jobId||null,queued:this.queue.length,browser:this.arbiter.health()};}
 get(id){if(!/^[a-f0-9-]{36}$/i.test(String(id||'')))return null;const file=path.join(this.jobs,id,'status.json');return fs.existsSync(file)?read(file):null;}
 _set(id,p){const f=path.join(this.jobs,id,'status.json');const n={...read(f),...p,updated_at:new Date().toISOString()};write(f,n);return n;}
 create(r){const allowed=new Set(['request_key','analysis_id','analysis_type','package_sha256','incoming_relative_path']);if(!r||typeof r!=='object'||Object.keys(r).some(k=>!allowed.has(k)))throw new Error('INVALID_REQUEST');if(!/^[a-f0-9]{64}$/i.test(r.request_key)||!/^[a-f0-9-]{36}$/i.test(r.analysis_id)||!/^[a-f0-9]{64}$/i.test(r.package_sha256))throw new Error('INVALID_REQUEST');const existing=fs.readdirSync(this.jobs,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>this.get(e.name)).find(s=>s?.request_key===r.request_key);if(existing)return existing;const relative=String(r.incoming_relative_path||'').replace(/\\/g,'/');if(!new RegExp(`^incoming/${r.package_sha256}/package\\.json$`,'i').test(relative))throw new Error('INVALID_PACKAGE_PATH');const source=path.resolve(this.root,...relative.split('/'));if(!fs.existsSync(source)||!inside(this.root,source)||fs.statSync(source).size>65536)throw new Error('INVALID_PACKAGE_PATH');const raw=fs.readFileSync(source,'utf8').trim();if(crypto.createHash('sha256').update(raw).digest('hex')!==r.package_sha256)throw new Error('PACKAGE_HASH');const pkg=JSON.parse(raw);validatePackage(pkg);if(pkg.analysis_id!==r.analysis_id||pkg.analysis_type!==r.analysis_type)throw new Error('PACKAGE_BINDING');const id=crypto.randomUUID();const dir=path.join(this.jobs,id);fs.mkdirSync(path.join(dir,'input'),{recursive:true});fs.mkdirSync(path.join(dir,'output'),{recursive:true});fs.copyFileSync(source,path.join(dir,'input','package.json'));write(path.join(dir,'manifest.json'),{schema_version:'NEXT_STABIL_ANALYSIS_JOB_V1',job_id:id,analysis_id:r.analysis_id,analysis_type:r.analysis_type,package_sha256:r.package_sha256,package:pkg,relative_input_path:'input/package.json'});const now=new Date().toISOString();const status={job_id:id,request_key:r.request_key,state:'QUEUED',attempt_count:0,error_code:null,created_at:now,updated_at:now};write(path.join(dir,'status.json'),status);fs.rmSync(path.join(this.incoming,r.package_sha256),{recursive:true,force:true});this.queue.push(id);this.pump();return status;}
 pump(){if(this.active||this.pausedState||!this.queue.length)return;const id=this.queue.shift();const s=this.get(id);if(!s||s.state!=='QUEUED')return this.pump();this.arbiter.acquire('analysis',id,()=>this._start(id));}
 _start(id){const s=this.get(id);if(!s||s.state!=='QUEUED'){this.arbiter.release('analysis',id);return this.pump();}const attempt=s.attempt_count+1;this._set(id,{state:'RUNNING',attempt_count:attempt});const child=this.spawnWorker(path.join(this.jobs,id));this.active={jobId:id,child};child.on('close',code=>{this.active=null;const latest=this.get(id);if(latest?.state==='CANCELLED'){this.arbiter.release('analysis',id);this.pump();return;}const text=String(child.analysisOutput||'');if(code===0)this._set(id,{state:'COMPLETE',error_code:null,temporary_chat_verified:text.includes('TEMPORARY_CHAT_VERIFIED')});else if(code===20||text.includes('AUTH_REQUIRED')){this.pausedState='AUTH_REQUIRED';this.arbiter.pause('AUTH_REQUIRED');this._set(id,{state:'AUTH_REQUIRED',error_code:'AUTH_REQUIRED'});}else if(code===21||text.includes('UI_CHANGED')){this.pausedState='UI_CHANGED';this.arbiter.pause('UI_CHANGED');this._set(id,{state:'UI_CHANGED',error_code:'UI_CHANGED'});}else this._set(id,{state:'FAILED',error_code:(/WORKER_ERROR_CODE=([A-Z0-9_]+)/.exec(text)||[])[1]||'WORKER_FAILED'});this.arbiter.release('analysis',id);this.pump();});}
 cancel(id){const s=this.get(id);if(!s)return null;if(this.active?.jobId===id){fs.writeFileSync(path.join(this.jobs,id,'cancel.requested'),'');this.active.child.kill();}this.queue=this.queue.filter(x=>x!==id);this.arbiter.cancel('analysis',id);return this._set(id,{state:'CANCELLED',error_code:null});}
 resume(){this.pausedState=null;this.arbiter.resume();for(const e of fs.readdirSync(this.jobs,{withFileTypes:true})){if(!e.isDirectory())continue;const s=this.get(e.name);if(s&&['AUTH_REQUIRED','UI_CHANGED'].includes(s.state)&&s.attempt_count<2){this._set(e.name,{state:'QUEUED',error_code:null});this.queue.push(e.name);}}this.pump();return this.health();}
 _spawn(dir){const nested=path.join(this.workerRoot,'worker','node_modules');const workerModules=fs.existsSync(nested)?nested:path.join(this.workerRoot,'node_modules');const inherited=process.env.NODE_PATH?`${process.env.NODE_PATH}${path.delimiter}${workerModules}`:workerModules;const child=spawn(process.execPath,[this.workerScript,dir],{cwd:path.dirname(this.workerScript),windowsHide:false,shell:false,env:{...process.env,NODE_PATH:inherited,NEXT_STABIL_VISION_WORKER_ROOT:this.workerRoot}});let out='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>out+=c);child.on('close',()=>child.analysisOutput=out);return child;}
 cleanup(ttl=72*60*60*1000){const cutoff=Date.now()-ttl;let removed=0;for(const e of fs.readdirSync(this.jobs,{withFileTypes:true})){if(!e.isDirectory())continue;const s=this.get(e.name);if(s&&['COMPLETE','FAILED','CANCELLED'].includes(s.state)&&Date.parse(s.updated_at)<cutoff){fs.rmSync(path.join(this.jobs,e.name),{recursive:true,force:true});removed++;}}return removed;}
}
module.exports={AnalysisQueue,inside};
