'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path');const {EventEmitter}=require('events');
const {AnalysisQueue}=require('./analysis_queue');const {VisionQueue}=require('./vision_queue');const {TemporaryChatArbiter}=require('./temporary_chat_arbiter');const {validateResult}=require('../vision-worker/analysis_contract');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'analysis-queue-')),analysisRoot=path.join(root,'analysis'),visionRoot=path.join(root,'vision');const arbiter=new TemporaryChatArbiter();const analysisChildren=[],visionChildren=[];
const packageValue={schema_version:'NEXT_STABIL_ADVANCED_ANALYSIS_V1',analysis_id:crypto.randomUUID(),analysis_type:'technical_interpretation',problem:'Synthetic public technical fixture',sources:[{source_ref:'S1',technical_excerpt:'R = U / I',page:1}],tables:[],formulas:[],variables:{},values:{},units:{},constraints:[],requested_output:'result',validation_requirements:[]};
const canonical=JSON.stringify(packageValue);const packageHash=crypto.createHash('sha256').update(canonical).digest('hex');const requestKey='a'.repeat(64);const incoming=path.join(analysisRoot,'incoming',packageHash);fs.mkdirSync(incoming,{recursive:true});fs.writeFileSync(path.join(incoming,'package.json'),canonical);
const visionKey='b'.repeat(64),visionIncoming=path.join(visionRoot,'incoming',visionKey);fs.mkdirSync(visionIncoming,{recursive:true});fs.writeFileSync(path.join(visionIncoming,'S1.png'),'synthetic');const visionHash=crypto.createHash('sha256').update('synthetic').digest('hex');
function child(list){const c=new EventEmitter();c.kill=()=>{};list.push(c);return c;}
const vision=new VisionQueue({spoolRoot:visionRoot,workerScript:'x',workerRoot:root,arbiter,spawnWorker:()=>child(visionChildren)});
const analysis=new AnalysisQueue({spoolRoot:analysisRoot,workerScript:'x',workerRoot:root,arbiter,spawnWorker:()=>child(analysisChildren)});
vision.create({request_key:visionKey,sources:[{source_ref:'S1',document_id:1,page_number:null,asset_id:null,sha256:visionHash,incoming_relative_path:`incoming/${visionKey}/S1.png`}]});
const created=analysis.create({request_key:requestKey,analysis_id:packageValue.analysis_id,analysis_type:packageValue.analysis_type,package_sha256:packageHash,incoming_relative_path:`incoming/${packageHash}/package.json`});
assert.strictEqual(visionChildren.length,1);assert.strictEqual(analysisChildren.length,0);assert.strictEqual(arbiter.health().owner_type,'vision');
visionChildren[0].visionOutput='TEMPORARY_CHAT_VERIFIED';visionChildren[0].emit('close',0);
setImmediate(()=>{assert.strictEqual(analysisChildren.length,1);assert.strictEqual(arbiter.health().owner_type,'analysis');analysisChildren[0].analysisOutput='TEMPORARY_CHAT_VERIFIED';analysisChildren[0].emit('close',0);setImmediate(()=>{assert.strictEqual(analysis.get(created.job_id).state,'COMPLETE');assert.throws(()=>analysis.create({...created,command:'whoami'}),/INVALID/);const manifest=JSON.parse(fs.readFileSync(path.join(analysisRoot,'jobs',created.job_id,'manifest.json')));assert.throws(()=>validateResult({schema_version:'NEXT_STABIL_ADVANCED_ANALYSIS_RESULT_V1',analysis_id:packageValue.analysis_id,package_sha256:packageHash,result:{},source_refs:['S8'],assumptions:[],uncertainties:[],constraints_checked:[],normalized_units:{},formula_used:null,calculation_steps:[],verification_recommendation:'accept'},manifest),/SOURCE/);
const pauseArbiter=new TemporaryChatArbiter();let deferredStarted=false;pauseArbiter.acquire('analysis','auth-job',()=>{});pauseArbiter.acquire('vision','waiting-job',()=>{deferredStarted=true;});pauseArbiter.pause('AUTH_REQUIRED');pauseArbiter.release('analysis','auth-job');assert.strictEqual(deferredStarted,false);assert.strictEqual(pauseArbiter.health().paused_state,'AUTH_REQUIRED');pauseArbiter.resume();setImmediate(()=>{assert.strictEqual(deferredStarted,true);fs.rmSync(root,{recursive:true,force:true});process.stdout.write('ANALYSIS QUEUE + GLOBAL SERIALIZATION: OK\n');});});});
