'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');

const helper = fs.readFileSync(path.join(__dirname, '..', 'hardening', 'invoke-qdrant-backup-helper.ps1'), 'utf8');
const backup = fs.readFileSync(path.join(__dirname, '..', 'hardening', 'backup-production.ps1'), 'utf8');

assert.match(helper, /NEXT_STABIL_QDRANT_BACKUP_HELPER_REQUEST_V1/);
assert.match(helper, /NEXT_STABIL_QDRANT_BACKUP_HELPER_RESULT_V1/);
assert.match(helper, /Resolve-NsR26CollectionSnapshotPath/);
assert.match(helper, /Get-NsR26DockerContainerInspection/);
assert.match(helper, /ConvertFrom-NsR26DockerInspectionCapture/);
assert.match(helper, /Get-NsR26QdrantStorageMount/);
assert.match(helper, /QDRANT_STORAGE_MOUNT_MISSING/);
assert.match(helper, /QDRANT_STORAGE_MOUNT_AMBIGUOUS/);
assert.match(helper, /QDRANT_STORAGE_MOUNT_NOT_VOLUME/);
assert.match(helper, /QDRANT_STORAGE_VOLUME_NAME_MISSING/);
assert.doesNotMatch(helper, /\{\{/);
assert.doesNotMatch(helper, /\}\}/);
assert.doesNotMatch(helper, /docker(?:\.exe)?\s+inspect\s+(?:-f|--format)\b/i);
assert.doesNotMatch(helper, /docker(?:\.exe)?\s+ps\s+--format\b/i);
assert.match(helper, /Join-Path \$collectionRoot \$SnapshotName/);
assert.match(helper, /SNAPSHOT_REPARSE_REJECTED/);
assert.match(helper, /'stop', '-t', '60', 'qdrant'/);
assert.match(helper, /'--pull', 'never'/);
assert.match(helper, /source=\$volume,target=\/qdrant\/storage/);
assert.match(helper, /QDRANT__STORAGE__SNAPSHOTS_PATH=\/qdrant\/snapshots/);
assert.match(helper, /QDRANT__STORAGE__TEMP_PATH=\/qdrant\/snapshots\/temp/);
assert.ok(helper.indexOf("'stop', '-t', '60', 'qdrant'") < helper.indexOf("'run', '-d', '--name'"));
assert.ok(helper.indexOf("docker.exe rm -f $helperName") < helper.indexOf("'start', 'qdrant'"));
assert.match(helper, /QDRANT_PRIMARY_IDENTITY_CHANGED/);
assert.match(helper, /QDRANT_POST_STATE_MISMATCH/);
assert.match(helper, /staging_residue_count/);
assert.match(helper, /helper_container_residue_count/);
assert.match(helper, /Invoke-NsR26QdrantHttpCapture/);
assert.match(helper, /ARTIFACT_RECONCILED_AFTER_HTTP_500/);
assert.match(helper, /QDRANT_HTTP500_CHECKSUM_MISSING/);
assert.match(helper, /qdrant-helper-container-logs\.txt/);
assert.match(helper, /checksum_file_sha256/);
assert.match(backup, /Invoke-QdrantHelperProcess/);
assert.match(backup, /ReadToEndAsync/);
assert.match(backup, /qdrant-helper-result\.json/);
assert.match(backup, /valid_external_f_staging/);
assert.match(backup, /checksum_artifact/);
assert.match(backup, /snapshot\.checksum/);
console.log('QDRANT_BACKUP_HELPER_CONTRACT=PASS');
