services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Europe/Warsaw
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http

    volumes:
      - ../../data/n8n:/home/node/.n8n

    networks:
      - ai-lab-network

networks:
  ai-lab-network:
    external: true
