"""add document page render metadata

Revision ID: 05b237160781
Revises: 365466d2b6d3
Create Date: 2026-08-10 20:33:12.346546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b237160781'
down_revision: Union[str, Sequence[str], None] = '365466d2b6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_pages', sa.Column('render_path', sa.String(length=2000), nullable=True))
    op.add_column('document_pages', sa.Column('render_dpi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_pages', 'render_dpi')
    op.drop_column('document_pages', 'render_path')
    # ### end Alembic commands ###
