"""upgrade document chunks for knowledge layer

Revision ID: 98987aa23248
Revises: 844bcf408c63
Create Date: 2026-08-12 17:42:01.769609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98987aa23248'
down_revision: Union[str, Sequence[str], None] = '844bcf408c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_from', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('page_to', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_type', sa.String(length=50), server_default='document', nullable=False))
    op.add_column('document_chunks', sa.Column('content_source', sa.String(length=50), server_default='combined', nullable=False))
    op.add_column('document_chunks', sa.Column('character_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_chunks', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('document_chunks', sa.Column('chunking_version', sa.String(length=50), server_default='v1', nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_status', sa.String(length=30), server_default='pending', nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_version', sa.String(length=100), nullable=True))
    op.add_column('document_chunks', sa.Column('vector_id', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_error', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_chunks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_chunks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_document_chunks_chunking_version', 'document_chunks', ['chunking_version'], unique=False)
    op.create_index('ix_document_chunks_content_hash', 'document_chunks', ['content_hash'], unique=False)
    op.create_index('ix_document_chunks_document_page', 'document_chunks', ['document_id', 'page_from', 'page_to'], unique=False)
    op.create_index('ix_document_chunks_embedding_status', 'document_chunks', ['embedding_status'], unique=False)
    op.create_unique_constraint('uq_document_chunks_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunks_document_chunk_index', 'document_chunks', type_='unique')
    op.drop_index('ix_document_chunks_embedding_status', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_page', table_name='document_chunks')
    op.drop_index('ix_document_chunks_content_hash', table_name='document_chunks')
    op.drop_index('ix_document_chunks_chunking_version', table_name='document_chunks')
    op.drop_column('document_chunks', 'updated_at')
    op.drop_column('document_chunks', 'created_at')
    op.drop_column('document_chunks', 'embedded_at')
    op.drop_column('document_chunks', 'embedding_error')
    op.drop_column('document_chunks', 'vector_id')
    op.drop_column('document_chunks', 'embedding_version')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'embedding_status')
    op.drop_column('document_chunks', 'chunking_version')
    op.drop_column('document_chunks', 'content_hash')
    op.drop_column('document_chunks', 'character_count')
    op.drop_column('document_chunks', 'content_source')
    op.drop_column('document_chunks', 'source_type')
    op.drop_column('document_chunks', 'page_to')
    op.drop_column('document_chunks', 'page_from')
    # ### end Alembic commands ###
