"""add import staging tables

Revision ID: f497dd01236f
Revises: 7f3c2d9a8b10
Create Date: 2026-08-02 20:07:02.216512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f497dd01236f'
down_revision: Union[str, Sequence[str], None] = '7f3c2d9a8b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sources',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('external_account_id', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='inactive', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_type IN ('gmail', 'google_sheets')", name='ck_import_sources_source_type'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'error')", name='ck_import_sources_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_sources_external_account_id', 'import_sources', ['external_account_id'], unique=False)
    op.create_index('ix_import_sources_source_type', 'import_sources', ['source_type'], unique=False)
    op.create_index('ix_import_sources_status', 'import_sources', ['status'], unique=False)
    op.create_table('import_runs',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('candidates_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicates_detected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cursor_before', sa.String(length=1000), nullable=True),
    sa.Column('cursor_after', sa.String(length=1000), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'partial', 'failed', 'cancelled')", name='ck_import_runs_status'),
    sa.CheckConstraint("trigger_type IN ('manual', 'scheduled', 'webhook')", name='ck_import_runs_trigger_type'),
    sa.ForeignKeyConstraint(['source_id'], ['import_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_runs_source_id', 'import_runs', ['source_id'], unique=False)
    op.create_index('ix_import_runs_started_at', 'import_runs', ['started_at'], unique=False)
    op.create_index('ix_import_runs_status', 'import_runs', ['status'], unique=False)
    op.create_table('client_candidates',
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('client_type', sa.String(length=30), server_default='other', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('building_number', sa.String(length=50), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='PL', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('matched_client_id', sa.BigInteger(), nullable=True),
    sa.Column('source_summary', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("client_type IN ('company', 'person', 'institution', 'other')", name='ck_client_candidates_client_type'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'merged', 'duplicate')", name='ck_client_candidates_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_client_candidates_confidence_range'),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_candidates_import_run_id', 'client_candidates', ['import_run_id'], unique=False)
    op.create_index('ix_client_candidates_matched_client_id', 'client_candidates', ['matched_client_id'], unique=False)
    op.create_index('ix_client_candidates_primary_email', 'client_candidates', ['primary_email'], unique=False)
    op.create_index('ix_client_candidates_status', 'client_candidates', ['status'], unique=False)
    op.create_index('ix_client_candidates_tax_id', 'client_candidates', ['tax_id'], unique=False)
    op.create_table('candidate_sources',
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('import_source_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=1000), nullable=False),
    sa.Column('external_parent_id', sa.String(length=1000), nullable=True),
    sa.Column('source_label', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_type IN ('gmail_message', 'gmail_thread', 'google_sheets_row')", name='ck_candidate_sources_source_type'),
    sa.ForeignKeyConstraint(['candidate_id'], ['client_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_source_id'], ['import_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_source_id', 'source_type', 'external_id', name='uq_candidate_sources_external_reference')
    )
    op.create_index('ix_candidate_sources_candidate_id', 'candidate_sources', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_sources_external_id', 'candidate_sources', ['external_id'], unique=False)
    op.create_index('ix_candidate_sources_import_run_id', 'candidate_sources', ['import_run_id'], unique=False)
    op.create_index('ix_candidate_sources_import_source_id', 'candidate_sources', ['import_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_sources_import_source_id', table_name='candidate_sources')
    op.drop_index('ix_candidate_sources_import_run_id', table_name='candidate_sources')
    op.drop_index('ix_candidate_sources_external_id', table_name='candidate_sources')
    op.drop_index('ix_candidate_sources_candidate_id', table_name='candidate_sources')
    op.drop_table('candidate_sources')
    op.drop_index('ix_client_candidates_tax_id', table_name='client_candidates')
    op.drop_index('ix_client_candidates_status', table_name='client_candidates')
    op.drop_index('ix_client_candidates_primary_email', table_name='client_candidates')
    op.drop_index('ix_client_candidates_matched_client_id', table_name='client_candidates')
    op.drop_index('ix_client_candidates_import_run_id', table_name='client_candidates')
    op.drop_table('client_candidates')
    op.drop_index('ix_import_runs_status', table_name='import_runs')
    op.drop_index('ix_import_runs_started_at', table_name='import_runs')
    op.drop_index('ix_import_runs_source_id', table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index('ix_import_sources_status', table_name='import_sources')
    op.drop_index('ix_import_sources_source_type', table_name='import_sources')
    op.drop_index('ix_import_sources_external_account_id', table_name='import_sources')
    op.drop_table('import_sources')
    # ### end Alembic commands ###
