'use strict';
const crypto=require('crypto');
const PACKAGE_SCHEMA='NEXT_STABIL_ADVANCED_ANALYSIS_V1';
const RESULT_SCHEMA='NEXT_STABIL_ADVANCED_ANALYSIS_RESULT_V1';
const TYPES=new Set(['technical_interpretation','formula_calculation','table_analysis','standards_comparison','consistency_check','document_interpretation','visual_analysis']);
function object(v,c){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(c);}
function validatePackage(v){object(v,'PACKAGE_INVALID');const allowed=new Set(['schema_version','analysis_id','analysis_type','problem','sources','tables','formulas','variables','values','units','constraints','requested_output','validation_requirements']);if(Object.keys(v).some(k=>!allowed.has(k)))throw new Error('PACKAGE_UNKNOWN_FIELD');if(v.schema_version!==PACKAGE_SCHEMA||!TYPES.has(v.analysis_type))throw new Error('PACKAGE_SCHEMA');if(!/^[a-f0-9-]{36}$/i.test(String(v.analysis_id||'')))throw new Error('PACKAGE_ANALYSIS_ID');if(!Array.isArray(v.sources)||v.sources.length<1||v.sources.length>8)throw new Error('PACKAGE_SOURCES');const refs=new Set();for(const s of v.sources){object(s,'PACKAGE_SOURCE');if(Object.keys(s).some(k=>!['source_ref','technical_excerpt','page'].includes(k)))throw new Error('PACKAGE_SOURCE_FIELD');if(!/^S[1-8]$/.test(s.source_ref)||refs.has(s.source_ref))throw new Error('PACKAGE_SOURCE_REF');refs.add(s.source_ref);if(typeof s.technical_excerpt!=='string'||s.technical_excerpt.length>2000)throw new Error('PACKAGE_EXCERPT');}return refs;}
function validateResult(v,m){object(v,'RESULT_INVALID');const allowed=new Set(['schema_version','analysis_id','package_sha256','result','source_refs','assumptions','uncertainties','constraints_checked','normalized_units','formula_used','calculation_steps','verification_recommendation']);if(Object.keys(v).some(k=>!allowed.has(k)))throw new Error('RESULT_UNKNOWN_FIELD');if(v.schema_version!==RESULT_SCHEMA||v.analysis_id!==m.analysis_id||v.package_sha256!==m.package_sha256)throw new Error('RESULT_BINDING');const refs=validatePackage(m.package);if(!Array.isArray(v.source_refs)||v.source_refs.some(r=>!refs.has(r)))throw new Error('RESULT_UNKNOWN_SOURCE_REF');if(!['accept','review','reject'].includes(v.verification_recommendation))throw new Error('RESULT_RECOMMENDATION');return v;}
function canonicalHash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');}
module.exports={PACKAGE_SCHEMA,RESULT_SCHEMA,validatePackage,validateResult,canonicalHash};
